// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFDets8m6tK6yX00hjcFJedTF_7feCELw',
    appId: '1:731114649187:web:f702af437456fecb93aa56',
    messagingSenderId: '731114649187',
    projectId: 'tcg-calculator',
    authDomain: 'tcg-calculator.firebaseapp.com',
    storageBucket: 'tcg-calculator.appspot.com',
    measurementId: 'G-KTYC5G21P9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABKQPmF411jAhrwlsahWiORePvPZe2Tk8',
    appId: '1:731114649187:android:b329b058075eb21b93aa56',
    messagingSenderId: '731114649187',
    projectId: 'tcg-calculator',
    storageBucket: 'tcg-calculator.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBY79qlFf7-sLlzL0MCZ-CDYCQXKCvzSX4',
    appId: '1:731114649187:ios:83f01065584f931393aa56',
    messagingSenderId: '731114649187',
    projectId: 'tcg-calculator',
    storageBucket: 'tcg-calculator.appspot.com',
    iosClientId: '731114649187-rdobs3vs7bf4v2rbe7js7egjevi0utee.apps.googleusercontent.com',
    iosBundleId: 'com.example.myBlocUtFlutterProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBY79qlFf7-sLlzL0MCZ-CDYCQXKCvzSX4',
    appId: '1:731114649187:ios:e23ee44b295e933393aa56',
    messagingSenderId: '731114649187',
    projectId: 'tcg-calculator',
    storageBucket: 'tcg-calculator.appspot.com',
    iosClientId: '731114649187-nambggphkk03cm8jjg4dtqbpjs7lfelh.apps.googleusercontent.com',
    iosBundleId: 'com.example.myBlocUtFlutterProject.RunnerTests',
  );
}
